package com.gmail.takenokoii78.toverie.analyze

enum class ExpressionSymbol(val value: String) {
    COMMA(','),
    DOT('.'),
    SINGLE_QUOTE('\''),
    DOUBLE_QUOTE('"'),
    ESCAPE('\\'),
    SEMICOLON (';'),
    PARENTHESIS_START('('),
    PARENTHESIS_END(')'),
    BRACE_START('{'),
    BRACE_END('}'),
    ARRAY_START('['),
    ARRAY_END(']'),
    ASSIGN('='),
    PLUS_ASSIGN("+="),
    MINUS_ASSIGN("-="),
    MULTIPLY_ASSIGN("*="),
    DIVIDE_ASSIGN("/="),
    MOD_ASSIGN("%="),
    BIT_AND_ASSIGN("&="),
    BIT_OR_ASSIGN("|="),
    BIT_XOR_ASSIGN("^="),
    POWER_ASSIGN("**="),
    LOGICAL_EQUALS("=="),
    LOGICAL_LESS('<'),
    LOGICAL_MORE('>'),
    LOGICAL_LESS_OR_EQUALS("<="),
    LOGICAL_MORE_OR_EQUALS(">="),
    LOGICAL_NOT_EQUALS("!="),
    COLON(':'),
    WHITESPACE(' '),
    LINEBREAK('\n'),
    CARRIAGE_RETURN('\r'),
    PLUS('+'),
    MINUS('-'),
    MULTIPLY('*'),
    DIVIDE('/'),
    MOD('%'),
    POWER("**"),
    LOGICAL_AND("&&"),
    LOGICAL_OR("||"),
    LOGICAL_NOT('!'),
    BIT_NOT('~'),
    BIT_AND('&'),
    BIT_OR('|'),
    BIT_XOR('^'),
    BIT_SHIFT_LEFT("<<"),
    BIT_SHIFT_LEFT_ASSIGN("<<="),
    BIT_SHIFT_RIGHT_ASSIGN(">>="),
    BIT_SHIFT_RIGHT_UNSIGNED_ASSIGN(">>>="),
    OPTIONAL_CHAIN("?."),
    NULL_COALESCE("??"),
    ARROW("->"),
    INCREMENT("++"),
    DECREMENT("--"),
    QUESTION('?'),
    COMMENT("//"),
    COMMENT_START("/*"),
    COMMENT_END("*/"),
    HASH("#");

    constructor(char: Char) : this(char.toString())
}

val NUMBER_CHARS: Array<Char> = arrayOf('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
